// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['API_KEY'] ?? 'default_web_api_key',
    appId: '1:51721152076:web:78f805339cc81c3298f6e9',
    messagingSenderId: '51721152076',
    projectId: 'gamepedia-90766',
    authDomain: 'gamepedia-90766.firebaseapp.com',
    storageBucket: 'gamepedia-90766.appspot.com',
    measurementId: 'G-S6SXRRRQPT',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['API_KEY2'] ?? 'default_web_api_key',
    appId: '1:51721152076:android:7106bae91c5f3c2498f6e9',
    messagingSenderId: '51721152076',
    projectId: 'gamepedia-90766',
    storageBucket: 'gamepedia-90766.appspot.com',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['API_KEY3'] ?? 'default_web_api_key',
    appId: '1:51721152076:ios:de5c7045cf46c2df98f6e9',
    messagingSenderId: '51721152076',
    projectId: 'gamepedia-90766',
    storageBucket: 'gamepedia-90766.appspot.com',
    iosClientId: '51721152076-uqub73klgojk5p6vt91d5lv0nr0rr4st.apps.googleusercontent.com',
    iosBundleId: 'com.example.gamePedia',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['API_KEY4'] ?? 'default_web_api_key',
    appId: '1:51721152076:ios:de5c7045cf46c2df98f6e9',
    messagingSenderId: '51721152076',
    projectId: 'gamepedia-90766',
    storageBucket: 'gamepedia-90766.appspot.com',
    iosClientId: '51721152076-uqub73klgojk5p6vt91d5lv0nr0rr4st.apps.googleusercontent.com',
    iosBundleId: 'com.example.gamePedia',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['API_KEY5'] ?? 'default_web_api_key',
    appId: '1:51721152076:web:f977b902427b784598f6e9',
    messagingSenderId: '51721152076',
    projectId: 'gamepedia-90766',
    authDomain: 'gamepedia-90766.firebaseapp.com',
    storageBucket: 'gamepedia-90766.appspot.com',
    measurementId: 'G-ZMBN72MS4K',
  );
}
